package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

var kanaA = "ぁあかがさざただなはばぱまゃやらわァアカガサザタダナハバパマャヤラワ"
var kanaI = "ぃいきぎしじちぢにひびぴみりゐィイキギシジチヂニヒビピミリヰ"
var kanaU = "ぅうくぐすずつづぬふぶぷむゅゆるゥウクグスズツヅヌフブプムュユルヴ"
var kanaE = "ぇえけげせぜてでねへべぺめれゑェエケゲセゼテデネヘベペメレヱ"
var kanaO = "ぉおこごそぞとどのほぼぽもょよろをォオコゴソゾトドノホボポモョヨロヲ"
var kanaN = "んン"

func main() {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by genvoweltable; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", os.Getenv("GOPACKAGE"))
	fmt.Fprintf(&buf, "const (\n\tkanaTableStart = 0x3041\n\tkanaTableEnd   = 0x30ff\n)\n\n")
	fmt.Fprintf(&buf, "var kanaVowelTable = [...]byte{\n")
	for i := 0x3041; i <= 0x30ff; i++ {
		r := rune(i)

		switch {
		case strings.ContainsRune(kanaA, r):
			fmt.Fprintf(&buf, "\t0x61, // %c\n", r)
		case strings.ContainsRune(kanaI, r):
			fmt.Fprintf(&buf, "\t0x69, // %c\n", r)
		case strings.ContainsRune(kanaU, r):
			fmt.Fprintf(&buf, "\t0x75, // %c\n", r)
		case strings.ContainsRune(kanaE, r):
			fmt.Fprintf(&buf, "\t0x65, // %c\n", r)
		case strings.ContainsRune(kanaO, r):
			fmt.Fprintf(&buf, "\t0x6f, // %c\n", r)
		case strings.ContainsRune(kanaN, r):
			fmt.Fprintf(&buf, "\t0x6e, // %c\n", r)
		default:
			fmt.Fprintf(&buf, "\t0x00, // %c (unmapped)\n", r)
		}
	}
	fmt.Fprintf(&buf, "}\n\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	if err := os.WriteFile("vowel_table.go", formatted, 0644); err != nil {
		panic(err)
	}
}
